# permissions for end users to view projectdevelopmentstreams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: projectdevelopmentstream-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: project-controller
    app.kubernetes.io/part-of: project-controller
    app.kubernetes.io/managed-by: kustomize
  name: projectdevelopmentstream-viewer-role
rules:
- apiGroups:
  - projctl.konflux.dev
  resources:
  - projectdevelopmentstreams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - projctl.konflux.dev
  resources:
  - projectdevelopmentstreams/status
  verbs:
  - get
