# permissions for end users to view projectdevelopmentstreamtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: projectdevelopmentstreamtemplate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: project-controller
    app.kubernetes.io/part-of: project-controller
    app.kubernetes.io/managed-by: kustomize
  name: projectdevelopmentstreamtemplate-viewer-role
rules:
- apiGroups:
  - projctl.konflux.dev
  resources:
  - projectdevelopmentstreamtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - projctl.konflux.dev
  resources:
  - projectdevelopmentstreamtemplates/status
  verbs:
  - get
