---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - projctl.konflux.dev
  resources:
  - projectdevelopmentstreams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - projctl.konflux.dev
  resources:
  - projectdevelopmentstreams/finalizers
  verbs:
  - update
- apiGroups:
  - projctl.konflux.dev
  resources:
  - projectdevelopmentstreams/status
  verbs:
  - get
  - patch
  - update
