apiVersion: projctl.konflux.dev/v1beta1
kind: ProjectDevelopmentStream
metadata:
  name: pds-sample-w-relpln
spec:
  project: project-sample
  template:
    name: pdst-sample-w-relpln
    values:
    - name: version
      value: "4.4.0"
